/**
 * Tests for Cedar Policy Prompt File
 *
 * Task Group 2: Cedar Policy Prompt File
 * Tests prompt file loading and structure validation
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

// Path to the Cedar policy prompt file
const PROMPT_FILE_PATH = path.join(__dirname, '../../../resources/prompts/steering/cedar-policies.prompt.md');

describe('Cedar Policy Prompt File', () => {
  let promptContent: string;

  beforeEach(() => {
    // Load the prompt file content
    promptContent = fs.readFileSync(PROMPT_FILE_PATH, 'utf-8');
  });

  // Test 2.1.1: Prompt file loads correctly
  it('should load the Cedar policy prompt file successfully', () => {
    expect(promptContent).toBeTruthy();
    expect(promptContent.length).toBeGreaterThan(0);
  });

  // Test 2.1.2: Prompt contains required input schema placeholders
  it('should contain required input schema documentation', () => {
    // Check for security section in input schema
    expect(promptContent).toContain('dataSensitivity');
    expect(promptContent).toContain('complianceFrameworks');
    expect(promptContent).toContain('approvalGates');
    expect(promptContent).toContain('guardrailNotes');

    // Check for agent/tool section in input schema
    expect(promptContent).toContain('agents');
    expect(promptContent).toContain('allTools');
    expect(promptContent).toContain('agentToolMapping');
  });

  // Test 2.1.3: Prompt output format produces valid Cedar syntax
  it('should specify correct Cedar syntax format in output', () => {
    // Check for Cedar action format with triple underscore
    expect(promptContent).toContain('AgentCore::Action::');
    expect(promptContent).toContain('___'); // Triple underscore

    // Check for Gateway ARN placeholder
    expect(promptContent).toContain('AgentCore::Gateway::"{{GATEWAY_ARN}}"');

    // Check for forbid statement usage
    expect(promptContent).toContain('forbid');

    // Check for annotation format
    expect(promptContent).toContain('@annotation');
  });
});

describe('Cedar Prompt Structure', () => {
  let promptContent: string;

  beforeEach(() => {
    promptContent = fs.readFileSync(PROMPT_FILE_PATH, 'utf-8');
  });

  // Test: Prompt contains header comment requirement
  it('should document header comment format requirement', () => {
    expect(promptContent).toContain('Generated by Agentify from Step 4 security inputs');
  });

  // Test: Prompt contains all compliance frameworks
  it('should contain examples for all five compliance frameworks', () => {
    expect(promptContent).toContain('HIPAA');
    expect(promptContent).toContain('PCI-DSS');
    expect(promptContent).toContain('GDPR');
    expect(promptContent).toContain('SOC 2');
    expect(promptContent).toContain('FedRAMP');
  });

  // Test: Prompt contains claim name conventions
  it('should document intuitive claim name conventions', () => {
    // Data sensitivity claims
    expect(promptContent).toContain('clearance_level');

    // Role-based claims
    expect(promptContent).toContain('user_role');
    expect(promptContent).toContain('department');

    // Approval authority claims
    expect(promptContent).toContain('approval_authority');

    // Compliance claims
    expect(promptContent).toContain('pci_certified');
    expect(promptContent).toContain('hipaa_trained');
  });

  // Test: Prompt contains approval gate patterns (case-insensitive section headers)
  it('should contain approval gate policy patterns', () => {
    // Check for approval gate section headers (using mixed case as in prompt)
    expect(promptContent).toContain('Before external API calls');
    expect(promptContent).toContain('Before Data Modification'); // Section header uses title case
    expect(promptContent).toContain('Before Sending Recommendations'); // Section header uses title case
    expect(promptContent).toContain('Before Financial Transactions'); // Section header uses title case
  });

  // Test: Prompt contains production expansion note
  it('should include production expansion comment pattern', () => {
    expect(promptContent).toContain('Example - expand for production');
  });
});

describe('Cedar Syntax Rules', () => {
  let promptContent: string;

  beforeEach(() => {
    promptContent = fs.readFileSync(PROMPT_FILE_PATH, 'utf-8');
  });

  // Test: Documents .contains() for multi-value checks
  it('should document .contains() for multi-value claim checks', () => {
    expect(promptContent).toContain('.contains(');
  });

  // Test: Documents context.claims access pattern
  it('should document context.claims access pattern', () => {
    expect(promptContent).toContain('context.claims');
  });

  // Test: Documents context.input access pattern
  it('should document context.input access pattern', () => {
    expect(promptContent).toContain('context.input');
  });

  // Test: Documents when clause syntax
  it('should document when clause syntax', () => {
    expect(promptContent).toContain('when {');
  });
});
