/**
 * Workflow Execution Configuration
 *
 * Agentify uses a single deployment model: local subprocess execution.
 * The orchestration runs locally via agents/main.py, which calls agents
 * deployed to Bedrock AgentCore via Strands SDK.
 *
 * There is NO separate "AgentCore mode" or "HTTP mode" - only local execution.
 */

/**
 * Configuration for workflow execution
 * Defines how the Demo Viewer spawns the orchestration subprocess
 */
export interface WorkflowConfig {
  /**
   * Path to the entry script relative to workspace root
   * Generated by Kiro spec-driven development
   * @example "agents/main.py"
   */
  entryScript: string;

  /**
   * Path to the Python interpreter
   * @example ".venv/bin/python" or "python3"
   */
  pythonPath: string;

  /**
   * Orchestration pattern used by the workflow
   * Determines how agents coordinate
   */
  orchestrationPattern: 'graph' | 'swarm' | 'workflow';

  /**
   * List of agents in the workflow
   */
  agents: AgentDefinition[];

  /**
   * Connections between agents (for graph patterns)
   */
  edges: EdgeDefinition[];
}

/**
 * Definition of an agent in the workflow
 */
export interface AgentDefinition {
  /** Unique identifier for the agent */
  id: string;

  /** Human-readable name */
  name: string;

  /** Role description */
  role: string;
}

/**
 * Definition of an edge connecting two agents
 */
export interface EdgeDefinition {
  /** Source agent ID */
  from: string;

  /** Target agent ID */
  to: string;

  /** Optional condition for the edge (graph pattern only) */
  condition?: string;
}

/**
 * Validates that a workflow configuration has all required fields
 * @param config The config to validate
 * @returns True if the config is valid for execution
 */
export function isValidWorkflowConfig(config: Partial<WorkflowConfig>): config is WorkflowConfig {
  return (
    typeof config.entryScript === 'string' &&
    config.entryScript.length > 0 &&
    typeof config.pythonPath === 'string' &&
    config.pythonPath.length > 0
  );
}

/**
 * Gets a human-readable description of what's missing from the config
 * @param config The config to check
 * @returns Array of missing field descriptions
 */
export function getMissingConfigFields(config: Partial<WorkflowConfig>): string[] {
  const missing: string[] = [];

  if (!config.entryScript || config.entryScript.length === 0) {
    missing.push('Entry script path (workflow.entryScript)');
  }

  if (!config.pythonPath || config.pythonPath.length === 0) {
    missing.push('Python interpreter path (workflow.pythonPath)');
  }

  return missing;
}
