# =============================================================================
# Agentify Workflow Events DynamoDB Table
# =============================================================================
# Version: 1.0.0
# Description: Creates a DynamoDB table for storing workflow events emitted by
#              the agentify_observability Python decorators. These events are
#              displayed in the Agentify extension's Demo Viewer panel.
#
# =============================================================================
# DEPLOYMENT INSTRUCTIONS
# =============================================================================
#
# Option 1: AWS CLI (Recommended)
# -------------------------------
# Deploy:
#   aws cloudformation deploy \
#     --template-file infrastructure/dynamodb-table.yaml \
#     --stack-name agentify-workflow-events \
#     --region us-east-1
#
# Deploy with custom table name:
#   aws cloudformation deploy \
#     --template-file infrastructure/dynamodb-table.yaml \
#     --stack-name agentify-workflow-events \
#     --region us-east-1 \
#     --parameter-overrides TableName=my-custom-table-name
#
# Delete:
#   aws cloudformation delete-stack \
#     --stack-name agentify-workflow-events \
#     --region us-east-1
#
# Option 2: AWS Console
# ---------------------
# 1. Open AWS CloudFormation Console
# 2. Click "Create stack" > "With new resources"
# 3. Upload this template file
# 4. Enter stack name: agentify-workflow-events
# 5. Review parameters and deploy
#
# =============================================================================
# PAYLOAD SIZE CONSTRAINTS
# =============================================================================
#
# DynamoDB item size limit: 400KB
# Reserved for payload attribute: 350KB maximum
# Reserved for other attributes: 50KB headroom
#   - workflow_id, timestamp, event_type, agent_name, ttl
#   - DynamoDB attribute name overhead
#
# IMPORTANT: Payload truncation is the responsibility of event producers
# (Python decorators in agentify_observability package). The table itself
# does not enforce size limits - oversized items will fail to write.
#
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  DynamoDB table for Agentify workflow events. Stores telemetry data from
  Python observability decorators for real-time visualization in the
  Agentify Kiro IDE extension Demo Viewer panel.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Table Configuration
        Parameters:
          - TableName
    ParameterLabels:
      TableName:
        default: DynamoDB Table Name

Parameters:
  TableName:
    Type: String
    Default: agentify-workflow-events
    Description: >
      Name of the DynamoDB table for storing workflow events.
      Use different names to isolate environments (dev, staging, prod)
      or multiple users sharing the same AWS account.
    MinLength: 3
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z0-9_.-]+$
    ConstraintDescription: >
      Table name must be 3-255 characters and contain only
      alphanumeric characters, underscores, hyphens, and dots.

Resources:
  WorkflowEventsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref TableName

      # Key Schema
      # - workflow_id: Groups all events for a single workflow execution
      # - timestamp: Epoch milliseconds for efficient range queries
      KeySchema:
        - AttributeName: workflow_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

      # Attribute Definitions (only key attributes required)
      # Additional attributes (event_type, agent_name, payload) are schemaless
      AttributeDefinitions:
        - AttributeName: workflow_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N

      # On-demand capacity for unpredictable demo workloads
      BillingMode: PAY_PER_REQUEST

      # Server-side encryption using AWS managed keys
      SSESpecification:
        SSEEnabled: true

      # TTL Configuration
      # Events expire 24 hours after creation (set by event producers)
      # TTL value calculation: ttl = int(time.time()) + 86400
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

      # Tags for resource identification
      Tags:
        - Key: Application
          Value: Agentify
        - Key: Component
          Value: WorkflowEvents
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  TableName:
    Description: Name of the created DynamoDB table
    Value: !Ref WorkflowEventsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the DynamoDB table (for IAM policy configuration)
    Value: !GetAtt WorkflowEventsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
